services:
  - type: web
    name: datequiz-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_DB_HOST
        value: aws-0-ap-southeast-1.pooler.supabase.com
      - key: SUPABASE_DB_PORT
        value: 6543
      - key: SUPABASE_DB_NAME
        value: postgres
      - key: SUPABASE_DB_USER
        value: postgres.epluqupenltlffznbmcx
      - key: SUPABASE_DB_PASSWORD
        value: 9695700251@Rohit
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-frontend-app.onrender.com
      - key: EMAIL_USER
        value: schoolabe10@gmail.com
      - key: EMAIL_PASS
        value: ejmv hrau cogi qqxx

databases:
  - name: datequiz-db
    databaseName: datequiz_prod
    user: datequiz_user
    plan: free 